### ISSUE TITLE
Incompatibility with Terrain Control (Biome Bundle)

### ISSUE THREAD

**Issue by Guinaro** [TTFTCUTS/Pioneer#1]
Hi,
I would love to use this mod to develop my personal modpack based on terrain control.
However it seems that Pioneer doesn't correctly map the biomes for terrain control.
e.g. I was standing in a Birch Forest Biome (Id: 27) however on the generated map it was marked as an Ocean Biome.

Is it possible to make the 2 mods compatible?

Thanks,
Guinaro

**Comment by TTFTCUTS** [comment]
Pioneer directly uses the method which most generators use for getting biomes, so if terrain control is sidestepping that then it's doing something weird.

**Comment by Guinaro** [comment]
I recently discovered that TerrainControl has a bukkit version, which does have a biome map generating tool. So I will put out a request on their Github to enhance the forge version with the same mapping functionality.

Guinaro
